package: libfabric
version: "2.1.0"
tag: v%(version)s
variables:
  github_user: ofiwg
source: https://github.com/ofiwg/libfabric.git
requires:
  - gcc
  - curl
  - numactl
  - rdma-core
  - xpmem
  - cuda
  - gdrcopy
  - rocr-runtime
build_requires:
  - autotools
  - gmake
---
rsync -a --chmod=ug=rwX --delete --exclude '**/.git' "$SOURCEDIR"/ "$BUILDDIR"/

cd "$BUILDDIR"

# Fix Perl module path for autotools package
export PERL5LIB="${AUTOTOOLS_ROOT}/share/autoconf:${PERL5LIB}"

bash autogen.sh

[[ -f "$BUILDDIR/configure" ]] || { echo "ERROR: configure not generated by autogen.sh"; exit 1; }

configure_args=(
    "--prefix=${INSTALLROOT}"
    "--disable-dependency-tracking"
    "--disable-debug"
    "--disable-profile"
    "--disable-asan"
    "--disable-lsan"
    "--disable-tsan"
    "--disable-ubsan"
    "--enable-shared"
    "--disable-static"
    "--enable-shm"
    "--enable-sm2"
    "--enable-xpmem=${XPMEM_ROOT}"
    "--disable-sockets"
    "--enable-tcp"
    "--enable-udp"
    "--enable-verbs=${RDMA_CORE_ROOT}"
    "--disable-opx"
    "--disable-psm2"
    "--disable-psm3"
    "--disable-usnic"
    "--disable-efa"
    "--disable-cxi"
    "--disable-mrail"
    "--disable-lpp"
    "--disable-ucx"
    "--enable-rxm"
    "--enable-lnx"
)

# CUDA configuration
if [[ -n "$CUDA_ROOT" ]]; then
    configure_args+=(
        "--enable-cuda-dlopen"
        "--enable-gdrcopy-dlopen"
        "--with-cuda=${CUDA_ROOT}"
        "--with-gdrcopy=${GDRCOPY_ROOT}"
    )
else
    configure_args+=(
        "--disable-cuda-dlopen"
        "--disable-gdrcopy-dlopen"
        "--without-cuda"
        "--without-gdrcopy"
    )
fi

# ROCm configuration
if [[ -n "$ROCM_ROOT" ]]; then
    configure_args+=(
        "--enable-rocr-dlopen"
        "--with-rocr=${ROCM_ROOT}"
    )
else
    configure_args+=(
        "--disable-rocr-dlopen"
        "--without-rocr"
    )
fi

configure_args+=(
    "--disable-ze-dlopen"
    "--without-ze"
    "--with-pic"
    "--with-dlopen"
    "--with-gnu-ld"
    "--with-curl=${CURL_ROOT}"
    "--with-numa=${NUMACTL_ROOT}"
)

"$BUILDDIR/configure" "${configure_args[@]}"
make ${JOBS:+-j$JOBS} -C "$BUILDDIR"
make -C "$BUILDDIR" install
