package: new-tools
version: v1
requires:
#- py-backports-zstd
- py-blinker
- py-choreographer
- py-colorlover
- py-dash-bootstrap-components
- py-dash-svg
- py-dash
- py-dnspython
- py-flask
- py-hepdata-validator
- py-itsdangerous
- py-jupyter-builder
- py-kaleido
- py-lit
- py-logistro
- py-mdit-py-plugins
- py-narwhals
- py-orjson
- py-pip
- py-plotext
- py-plotille
- py-plotly
- py-portpicker
- py-pyg-lib-cuda
- py-pyg-lib
- py-pymongo
- py-retrying
- py-setuptools
- py-simplejson
- py-tblib
- py-textual-fspicker
- py-textual-plotext
- py-textual
- py-triton
- py-xyzservices
---
