requires:
  - py-absl-py
  - py-aiohappyeyeballs
  - py-aiohttp
  - py-aiosqlite
  - py-aiosignal
  - py-annotated-types
  - py-anyio
  - py-appdirs
  - py-argon2-cffi
  - py-argon2-cffi-bindings
  - py-argparse
  - py-arrow
  - py-asn1crypto
  - py-astor
  - py-astroid
  - py-asttokens
  - py-astunparse
  - py-async-lru
  - py-async-timeout
  - py-atomicwrites
  - py-attrs
  - py-autopep8
  - py-avro
  - py-awkward
  - py-awkward-cpp
  - py-awkward-pandas
  - py-babel
  - py-backcall
  - py-backports-entry-points-selectable
  - py-backports-tarfile
  - py-beautifulsoup4
  - py-beniget
  - py-bleach
  - py-blosc
  - py-blosc2
  - py-bokeh
  - py-boost-histogram
  - py-bottle
  - py-Bottleneck
  - py-build
  - py-cachecontrol
  - py-cachetools
  - py-cachy
  - py-calver
  - py-charset-normalizer
  - py-chug
  - py-cleo
  - py-click
  - py-clikit
  - py-cmsml
  - py-cms-tfaot
  - py-contourpy
  - py-correctionlib
  - py-cramjam
  - py-crashtest
  - py-certifi
  - py-cffi
  - py-chardet
  - py-cloudpickle
  - py-colorama
  - py-comm
  - py-commonmark
  - py-conan
  - py-contextlib2
  - py-contextvars
  - py-coverage
  - py-cppy
  - py-cryptography
  - py-cx-Oracle
  - py-cycler
  - py-cython
  - py-dask
  - py-dask-awkward
  - py-decorator
  - py-debugpy
  - py-defusedxml
  - py-deprecation
  - py-deprecated
  - py-dill
  - py-distlib
  - py-distro
  - py-docopt
  - py-docutils
  - py-dulwich
  - py-editables
  - py-entrypoints
  - py-execnet
  - py-executing
  - py-exceptiongroup
  - py-expandvars
  - py-fasteners
  - py-fastjsonschema
  - py-filelock
  - py-fire
  - py-findpython
  - py-flit
  - py-flit-core
  - py-flit-scm
  - py-flake8
  - py-flatbuffers
  - py-flawfinder
  - py-fonttools
  - py-frozenlist
  - py-fsspec
  - py-funcsigs
  - py-future
  - py-gast
  - py-gitdb
  - py-GitPython
  - py-google-auth
  - py-google-auth-oauthlib
  - py-google-pasta
  - py-grpcio
  - py-grpcio-tools
  - py-h11
  - py-hatch-fancy-pypi-readme
  - py-hatch-jupyter-builder
  - py-hatch-nodejs-version
  - py-hatch-vcs
  - py-hatchling
  - py-h5py
  - py-hepdata-lib
  - py-hepdata-validator
  - py-hist
  - py-histoprint
  - py-histogrammar
  - py-html5lib
  - py-httpcore
  - py-httpx
  - py-idna
  - py-immutables
  - py-importlib-metadata
  - py-importlib-resources
  - py-iniconfig
  - py-installer
  - py-ipaddress
  - py-ipykernel
  - py-ipython_genutils
  - py-ipython
  - py-ipywidgets
  - py-isort
  - py-jaraco-classes
  - py-jaraco-functools
  - py-jaraco-context
  - py-jax
  - py-jaxlib
  - py-jedi
  - py-jeepney
  - py-Jinja2
  - py-jinja2-time
  - py-joblib
  - py-json5
  - py-jsonpickle
  - py-jsonschema
  - py-jsonschema-specifications
  - py-jupyter-client
  - py-jupyter-console
  - py-jupyter-core
  - py-jupyter-events
  - py-jupyter-packaging
  - py-jupyterlab-pygments
  - py-jupyter-lsp
  - py-jupyter-server
  - py-jupyterlab-server
  - py-jupyter-server-mathjax
  - py-jupyter-server-terminals
  - py-jupyterlab
  - py-jupyterlab-widgets
  - py-keras
  - py-keras-applications
  - py-keras-preprocessing
  - py-keras2onnx
  - py-keyring
  - py-kiwisolver
  - py-law
  - py-lazy-object-proxy
  - py-lizard
  - py-locket
  - py-lockfile
  - py-luigi
  - py-lxml
  - py-lz4
  - py-make
  - py-Mako
  - py-Markdown
  - py-markdown-it-py
  - py-MarkupSafe
  - py-matplotlib
  - py-matplotlib-inline
  - py-maturin
  - py-mccabe
  - py-mdurl
  - py-meson
  - py-meson-python
  - py-mistune
  - py-ml_dtypes
  - py-mock
  - py-more-itertools
  - py-mpld3
  - py-mplhep
  - py-mplhep-data
  - py-mpmath
  - py-msgpack
  - py-multidict
  - py-nbclassic
  - py-nbclient
  - py-nbconvert
  - py-nbformat
  - py-ndindex
  - py-nest-asyncio
  - py-networkx
  - py-neurolab
  - py-node-semver
  - py-notebook
  - py-notebook-shim
  - py-nvidia-ml-py
  - py-numexpr
  - py-numpy
  - py-onnx
  - py-onnxmltools
  - py-onnxconverter-common
  - py-oauthlib
  - py-opt-einsum
  - py-overrides
  - py-pkginfo
  - py-packaging
  - py-pandas
  - py-pandocfilters
  - py-parsimonious
  - py-parso
  - py-partd
  - py-pastel
  - py-patch-ng
  - py-pathlib2
  - py-pathspec
  - py-pbr
  - py-pbs-installer
  - py-pdm-backend
  - py-pexpect
  - py-pickleshare
  - py-pillow
  - py-pkgconfig
  - py-plac
  - py-platformdirs
  - py-pluginbase
  - py-pluggy
  - py-ply
  - py-poetry
  - py-poetry-core
  - py-poetry-plugin-export
  - py-prettytable
  - py-prometheus-client
  - py-prompt_toolkit
  - py-propcache
  - py-protobuf
  - py-prwlock
  - py-psutil
  - py-ptyprocess
  - py-pure-eval
  - py-py-cpuinfo
  - py-pyasn1-modules
  - py-pyasn1
  - py-pybind11
  - py-pybrain
  - py-pycodestyle
  - py-pycparser
  - py-pycuda
  - py-pycurl
  - py-pydantic-core
  - py-pydot
  - py-pyflakes
  - py-Pygments
  - py-PyJWT
  - py-pylint
  - py-pymongo
  - py-pyparsing
  - py-pyproject-hooks
  - py-pyproject-metadata
  - py-pyrsistent
  - py-pydantic
  - py-pygithub
  - py-pylev
  - py-PyNaCl
  - py-pysocks
  - py-pysqlite3
  - py-pytest
  - py-pytest-cov
  - py-pytest-runner
  - py-pytest-xdist
  - py-python-daemon
  - py-python-dateutil
  - py-python-json-logger
  - py-python-ldap
  - py-python-rapidjson
  - py-pythran
  - py-pytoml
  - py-pytools
  - py-pytz
  - py-PyYAML
  - py-pyzmq
  - py-rapidfuzz
  - py-referencing
  - py-regex
  - py-repoze-lru
  - py-rep
  - py-requests
  - py-requests-toolbelt
  - py-requests-oauthlib
  - py-requests-unixsocket
  - py-rfc3339-validator
  - py-rfc3986-validator
  - py-rich
  - py-rootpy
  - py-rpds-py
  - py-rsa
  - py-scandir
  - py-schema
  - py-scikit-build
  - py-scikit-build-core
  - py-scikit-learn
  - py-scinum
  - py-scipy
  - py-secretstorage
  - py-semantic-version
  - py-threadpoolctl
  - py-seaborn
  - py-Send2Trash
  - py-setuptools-rust
  - py-setuptools-scm
  - py-shellingham
  - py-simplegeneric
  - py-singledispatch
  - py-six
  - py-skl2onnx
  - py-smmap
  - py-sniffio
  - py-soupsieve
  - py-sqlalchemy
  - py-stack-data
  - py-stevedore
  - py-subprocess32
  - py-sympy
  - py-tables
  - py-tabulate
  - py-tenacity
  - py-tensorflow
  - py-tensorboard
  - py-tensorflow-io-gcs-filesystem
  - py-tensorflow-estimator
  - py-tensorboard-data-server
  - py-tensorboard-plugin-wit
  - py-termcolor
  - py-terminado
  - py-testpath
  - py-test-download
  - py-tinycss2
  - py-toml
  - py-tomli
  - py-tomli-w
  - py-tomlkit
  - py-toolz
  - py-tornado
  - py-tqdm
  - py-traitlets
  - py-trove-classifiers
  - py-typed-ast
  - py-types-python-dateutil
  - py-typing-extensions
  - py-typing-inspection
  - py-tzdata
  - py-uhi
  - py-uncertainties
  - py-uproot
  - py-urllib3
  - py-vector
  - py-versioneer
  - py-virtualenv-clone
  - py-virtualenv
  - py-virtualenvwrapper
  - py-wcwidth
  - py-webencodings
  - py-websocket-client
  - py-Werkzeug
  - py-wheel
  - py-widgetsnbextension
  - py-wrapt
  - py-xgboost
  - py-xxhash
  - py-yarl
  - py-zipp
  - py-iminuit
