# Shared variables for CMSSW, cmssw-tools, and cmssw-tool-conf.
# branch is derived from release_queue at build time and overrides the default below.

branch:                        master
configtag:                     V09-09-03
subpackageDebug:               yes
saveDeps:                      yes
runGlimpse:                    yes
buildtarget:                   release-build
scram_compiler:                gcc
enable_biglib:                 1
srctree:                       src
bootstrapfile:                 config/bootsrc.xml
skipreqtools:                  jcompiler opencl opencl-cpp intel-vtune icx-cxxcompiler icx-ccompiler icx-f77compiler mpich
override_microarch:            -march=x86-64-v2
default_microarch:             -march=x86-64-v2
min_microarch_name:            -march=x86-64-v2
vectorization:
package_vectorization:
vectorized_packages:
gpu_backend_specific_packages:
gpu_types:
usercxxflags:
scram_target_default:
release_usercxxflags:
release_userldflags:
extra_tools:                   
remove_tools:
compile_options:
nolibchecks:
prebuildtarget:
additionalBuildTarget0:
postbuildtarget:
ignore_compile_errors:
pgo_generate:
pgo_build_flags:
cuda_gcc_support:              1
use_system_gcc:                0
enable_frame_pointer:          1
use_cuda:                      1
use_rocm:                      1
HFI_NO_BACKTRACE:              1
IPATH_NO_BACKTRACE:            1
