#!/bin/sh
set -eu

TREE="${1:-$INSTALLROOT}"
OUTDIR="$INSTALLROOT/etc/deps"
mkdir -p "$OUTDIR"

SKIP_AUTOREQ="cuda cudnn oracle cmsswdata"

cp $BITS_CONFIG_DIR/hooks/check_dependencies.py $OUTDIR/

to_json() {
    sort -u | awk '
        BEGIN { printf "[" }
        { printf "%s%s", (NR>1 ? "," : ""), "\n  " ; gsub(/\\/,"\\\\"); gsub(/"/,"\\\""); printf "\"%s\"", $0 }
        END { print (NR ? "\n" : "") "]" }
    '
}

find "$TREE" -type f | /usr/lib/rpm/rpmdeps --provides | to_json > "$OUTDIR/provides.json"
find "$TREE" -type f | /usr/lib/rpm/rpmdeps --requires | to_json > "$OUTDIR/requires.json"

jq -r --arg arch "$ARCHITECTURE" '.dependencies.direct.runtime[] | "$WORK_DIR/\($arch)/*/\(.name)/\(.version)\(if .revision != null then "-\(.revision)" else "" end)/etc/deps/provides.json"' $INSTALLROOT/.meta.json > $OUTDIR/dependencies.json

echo "\$WORK_DIR/$ARCHITECTURE/system-provides.json" >> "$OUTDIR/dependencies.json"

if [[ ! " $SKIP_AUTOREQ " =~ " $PKGNAME " ]]; then
  cat << EoF >> "$INSTALLROOT/etc/profile.d/post-relocate.sh"
WORK_DIR=\$WORK_DIR \$WORK_DIR/\$PP/etc/deps/check_dependencies.py
EoF
fi
