name: Build Packages

on:
  push:
    branches:
      - IB/CMSSW_17_0_X/G14
  pull_request:
    branches:
      - IB/CMSSW_17_0_X/G14

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Clone and install bits build tool
        run: |
          git clone https://github.com/bitsorg/bits.git
          cd bits
          export PATH=$PWD:$PATH
          python -m venv .venv
          source .venv/bin/activate
          pip install -e .
      - name: Build go
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          cd bits
          source .venv/bin/activate
          bitsBuild build \
            --architecture el9_amd64_gcc14 \
            --force-unknown-architecture \
            --jobs 16 \
            --work-dir sw \
            -c ${{ github.workspace }} \
            --docker \
            --docker-image cmssw/el9:x86_64 \
            --sandbox off \
            --remote-store b3://bits::rw \
            --debug \
            go

      - name: Upload build logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: build-logs-go
          path: bits/sw/BUILD/go/latest/logs
          retention-days: 7
